module wallace(
	P1,
	P2,
	P3,
	P4,
	ab,
	clk,
	rstn);

	//---Ports declearation: generated by Robei---
	input [15:0] P1;
	input [15:0] P2;
	input [15:0] P3;
	input [15:0] P4;
	output [15:0] ab;
	input clk;
	input rstn;

	wire [15:0] P1;
	wire [15:0] P2;
	wire [15:0] P3;
	wire [15:0] P4;
	reg [15:0] ab;
	wire clk;
	wire rstn;

	//----Code starts here: integrated by Robei-----
	reg [15:0] p1,p2,p3,p4,i;
	
	always@(posedge clk or negedge rstn)
	begin
	if(!rstn)
	begin
	p1<=P1;
	p2<=P2;
	p3<=P3;
	p4<=P4;
	end
	else
	 begin
	  p2[15]<=p2[15]^p3[15]^p4[15];//第一次压缩
	  for(i=14;i>=7;i=i-1)
	  begin 
	    p3[i+1]<=(p2[i]&p3[i])|(p2[i]&p4[i])|(p4[i]&p3[i]);
	    p2[i]<=p2[i]^p3[i]^p4[i];
	  end
	  p3[7]<=p3[6]&p4[6];
	  p3[6]<=p3[6]^p4[6];
	  
	  p1[15]<=p1[15]^p2[15]^p3[15];//第二次压缩
	  for(i=14;i>=5;i=i-1)
	  begin 
	    p2[i+1]<=(p1[i]&p2[i])|(p1[i]&p3[i])|(p2[i]&p3[i]);
	    p1[i]<=p1[i]^p2[i]^p3[i];
	  end
	  p2[5]<=p2[4]&p3[4];
	  p2[4]<=p2[4]^p3[4];
	  p1<=p1+p2;
	  ab[15:0]<=p1[15:0];
	end
	end
endmodule    //wallace

